version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null
    volumes:
      - ..:/app
      - ./logs:/app/logs
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
    env_file:
      - ../.env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: 'rabbitmq:3.8-management'
    environment:
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
    ports:
      - '${RABBITMQ_PORT}:5672'
      - '${RABBITMQ_PORT_WEB}:15672'
    networks:
      default:
        aliases:
          - rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "node_health_check" ]
      interval: 30s
      timeout: 20s
      retries: 10
    env_file:
      - ../.env
volumes:
  redis_data:
  logs: